### ISSUE TITLE
Couldn't Connect to Retros

### ISSUE THREAD

**Issue by marcocorriero** [sirjonasxx/G-Earth#24]
Title says all.

**Comment by sirjonasxx** [comment]
If your issue wasnt described here: https://github.com/sirjonasxx/G-Earth/wiki/Troubleshooting, make a new issue where you include the required information. You didn't even give the hotelname, so I'm not sure what you actually expect.

We can't help you if this is you only include this information. However I will tell you that if the retro has a static connection.host IP, we can't help you at the moment. Otherwise, feel free to create a real issue
