### ISSUE TITLE
Unable to connect to retros.

### ISSUE THREAD

**Issue by marcocorriero** [sirjonasxx/G-Earth#27]
#24 

Well, the issue is (hotels like ) http://www.bssitalia.eu/ , bobba, or hotelspecial.it
im unable to connect with the packetlogger.

**Comment by sirjonasxx** [comment]
hotels like www.bssitalia.eu/ or hotelspecial.it do not work because they use a raw IP address. G-Earth currently only works for gameservers identified with a name (DNS) because we can override that.

If you do find a way to redirect traffic to a raw IP, feel free to let us know. The next release of G-Earth will have advanced tools included, allowing you to take the job of redirecting traffic on your own, and still use G-Earth

![image](https://user-images.githubusercontent.com/36828922/52164991-ee1bf580-26fa-11e9-850e-8837dae10778.png)

**Comment by marcocorriero** [comment]
@sirjonasxx Also, why you dont ask tanji's creator, somehow he found a way to redirect raw ip traffic using tanji

**Comment by sirjonasxx** [comment]
Well.. The advanced tools DO work but as I told you, YOU're the one in charge of redirecting traffic when using advanced tiiks.

Also, Tanji replaces the swf, we do not

**Comment by marcocorriero** [comment]
maybe instead of closing it, keep it open till we find a solution?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
