### ISSUE TITLE
Execution from code for development

### ISSUE THREAD

**Issue by K3RMADEC** [sirjonasxx/G-Earth#52]
Hello, 
I want to execute the code from my IDE (InteliJ) but the code can't found "G-WinMem.exe", How can I generate this exe?

I'm looking for developing a hotkey for enable/disable the packet scheduler (like in Tanji).

In Addition, I saw a option for override the connection in the "Extra" page, but I don't know how to make it works. I want to redirect the traffic to Habbo through my own server.

Thank you.

**Comment by XePeleato** [comment]
The source of G-WinMem is available on the windowsDev branch. You'll need Visual Studio in order to compile it, however, it's also possible to get it from the release page and just copy it to G-Earth's target/bin directory

**Comment by K3RMADEC** [comment]
Thank you so much.

Other question. How can I generate the "G-Earth.exe"? When I execute the maven install I only get the .jar file.

**Comment by XePeleato** [comment]
G-Earth.exe is just a way to run `java -jar G-Earth.jar` so it is not needed nor generated.

**Comment by sirjonasxx** [comment]
@K3RMADEC a little update on your question
> I want to execute the code from my IDE (InteliJ) but the code can't found "G-WinMem.exe", How can I generate this exe?

When clicking "package" in the maven lifecycle, G-Earth will now generate all necessary files in a "Build/" folder in the root directory (on the development brnach)
![image](https://user-images.githubusercontent.com/36828922/80269879-e061df80-86b3-11ea-8eb4-f192870df22a.png)
![image](https://user-images.githubusercontent.com/36828922/80269883-e48dfd00-86b3-11ea-8915-452a8ba798c5.png)
The included files are exactly the ones that will be included in releases
If you want to generate memorysearchers yourself, this part of the project has now moved to https://github.com/sirjonasxx/G-Mem

> I'm looking for developing a hotkey for enable/disable the packet scheduler (like in Tanji).

On the topic of scheduler hotkeys, its actually available but there was a spelling mistake (it said ctrl+alt+index instead of ctrl+shift+index) which has now been fixed on development
![image](https://user-images.githubusercontent.com/36828922/80269908-43ec0d00-86b4-11ea-96a0-b0688b1fec6f.png)
Feel free to create your own version with custom hotkeys. If you manage to make something nice, feel free to PR

> In Addition, I saw a option for override the connection in the "Extra" page, but I don't know how to make it works. I want to redirect the traffic to Habbo through my own server.

This was/is an experimental feature that lets you be in control over how packets are redirected to G-Earth. It's pretty not-tested and I'm not sure if it is very useful. If you want packets to be redirected to your own server, an extension is the way to go. Extensions can be made over the network and will redirect all traffic to you/your server
