### ISSUE TITLE
Concurrency (?) issue (IllegalStateException)

### ISSUE THREAD

**Issue by kSlideHH** [sirjonasxx/G-Earth#75]
Ref: https://discord.com/channels/528426152935555103/528429684632059916/793955359911444500
Bug report:
Cant send packets to server anymore, packet logger still working

Reproduction steps:

1. Use this extension
You will need my updates to G-Python of course (https://github.com/sirjonasxx/G-Python/pull/2)
```pip install -e /path/to/g_python/repo```
https://github.com/kSlideHH/autowalker_py

2. and see video (reproduce those steps)
https://workupload.com/file/rn4YRJTP3VF
Backup Link (the above is deleted after 14 days): https://workupload.com/file/fGY3MKe44wP

**Comment by kSlideHH** [comment]
I noticed that the extension process is sometimes interrupted when this occurs

**Comment by sirjonasxx** [comment]
This really doesn't seem like the latest downloadable version of G-Earth (according to error line numbers), please redownload and confirm you still have this issue. (I tried to reproduce with the steps you gave, but never got any error). Your error output also says "BasicRemote", but G-Earth uses "AsyncRemote" since a while
